### ISSUE TITLE
[v2.3.1] Resource not accessible by integration

### ISSUE THREAD

**Issue by yusancky** [thollander/actions-comment-pull-request#181]
First of all, thank you very much for developing such a useful and convenient Actions. 

I was using v2.3.0 and it worked very well and helped me simplify some of my work. But just now, @dependabot opened a new pull request yusancky/AllUp-Satwiki#9 in my repository, which wants to upgrade this Actions to v2.3.1. However, the pull request did not pass the test and no comment was given - it failed in The comment gives an error. 

> [Bump thollander/actions-comment-pull-request from 2.3.0 to 2.3.1 #43](https://github.com/yusancky/AllUp-Satwiki/actions/runs/3917944028/jobs/6698171460#step:7:108)
> 
> ```powershell
> Error: Resource not accessible by integration
> ```

Here's part of the workflow file. This workflow runs on `Ubuntu-latest`. 

```yaml
      - name: Preview on Pull Request
        if: ${{ github.event_name == 'pull_request' }}
        uses: thollander/actions-comment-pull-request@v2.3.1
        with:
          message: |
            # 预览
            ```go
            ${{ steps.fetch_make.outputs.ALLUP_CONTENT }}
            ```
            > **Note**
            > 上方的 wikitext 代码块因展示高亮便利而使用 Go 语言高亮器，敬请理解。
          reactions: eyes
          comment_tag: actions-wikitext-preview
```
