### ISSUE TITLE
Possibility to comment with a clickable images / badges with a link

### ISSUE THREAD

**Issue by ibuziuk** [thollander/actions-comment-pull-request#20]
Hello, really like the action, but it looks like it is not possible to comment with a clickable image / badge smth. like 

`[![Contribute](https://img.shields.io/badge/Eclipse_Che-Hosted%20by%20Red%20Hat-525C86?logo=eclipse-che&labelColor=FDB940)](https://workspaces.openshift.com/)`

in the comment, it should resolve to the following clickable badge [![Contribute](https://img.shields.io/badge/Eclipse_Che-Hosted%20by%20Red%20Hat-525C86?logo=eclipse-che&labelColor=FDB940)](https://workspaces.openshift.com/)

Currently, it is not parsed correctly by the action. Any pointers. Thanks!

**Comment by ibuziuk** [comment]
False alarm looks like it works just fine:

```
on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: Try the PR on Eclipse Che hosted by Red Hat
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Try the PR [![Contribute](https://img.shields.io/badge/Eclipse_Che-Hosted%20by%20Red%20Hat-525C86?logo=eclipse-che&labelColor=FDB940)](https://workspaces.openshift.com#https://github.com/${{ github.event.pull_request.head.repo.full_name }}/tree/${{ github.head_ref }})'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
