### ISSUE TITLE
Issue interpolating multiline outputs into the comment

### ISSUE THREAD

**Issue by neefrehman** [thollander/actions-comment-pull-request#209]
Hi!

I'm currently trying to add a comment to a PR with the results of an end-to-end snapshot test. The results are generated in a prior step and I interpolate the step's output into the `message` field of this action, but am struggling to get the comment to keep its multilined formatting.

Here is a minimal reproduction of my workflow:

```yaml
name: snapshot test
on: pull_request
jobs:
  api-regression-test:
    runs-on: ubuntu-latest
    steps:
      # [...steps to generate json snapshots and install the jd diffing utility]
      - name: Diff snapshot against canonical
        id: diff
        run: |
          # I've verified in CI that this output is being saved with multiple lines
          # I have also tried the >> $GITHUB_ENV method in referenced the github docs, with the same results
          SNAPSHOT_DIFF=$(jd current.json canonical.json)
          SNAPSHOT_DIFF="${SNAPSHOT_DIFF//'%'/'%25'}"
          SNAPSHOT_DIFF="${SNAPSHOT_DIFF//$'\n'/'%0A'}"
          SNAPSHOT_DIFF="${SNAPSHOT_DIFF//$'\r'/'%0D'}"
          echo "snapshot-diff=$SNAPSHOT_DIFF" >> $GITHUB_OUTPUT
      - name: Comment diff onto PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ```diff
            [...some metadata about diff]
            ${{ steps.diff.outputs.snapshot-diff }}
            ```
```

And here is the output that I get:

```diff
[...some metadata about diff]
@ ["loc1","loc2",loc3]%0A- {"key1":{"key2": "val1"}}%0A @ ["loc1","loc2",loc3]%0A- {"key1":{"key2": "val1"}}
```

Converting `\n` characters to `'%0A'`, as I'm doing in the `diff` step, is required to get outputs to not collapse onto one line. It also seems like `@actions/core` does this under the hood, as well.

But, the PR comment is outputting `%0A` where a newline should be. I'm not sure how to go about deserialising this output in the PR comment action in a way that allows for proper formatting. Is this something that there is an established pattern for?
