### ISSUE TITLE
Cannot utilize environment variable. Can you provide an example?

### ISSUE THREAD

**Issue by JDEDevOpsUser** [thollander/actions-comment-pull-request#218]

**Comment by thollander** [comment]
Use the [env context from Github](https://docs.github.com/en/actions/learn-github-actions/contexts#env-context).   

Here is an [example](https://github.com/thollander/actions-comment-pull-request/pull/221#issuecomment-1540276921) 

```yaml
on: pull_request

env: 
  FOO: BAR

jobs:
  env_var:
    name: Env var example
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR with message
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Foo value : ${{ env.FOO }}
```
