### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by mablinov** [thollander/actions-comment-pull-request#224]
Not an expert on github actions, something obvious i'm missing?

In my github actions log:

```
Run thollander/actions-comment-pull-request@v2.3.1
  with:
    GITHUB_TOKEN: ***
    pr_number: 1
    filePath: /home/runner/work/llvm-project/llvm-project/clang-format.patch
    mode: upsert
    create_if_not_exists: true
Error: Resource not accessible by integration
```

the code:

```yaml
    - name: Comment Pull Request
      uses: thollander/actions-comment-pull-request@v2.3.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        pr_number: ${{github.event.number}}
        filePath: ${{ github.workspace }}/clang-format.patch
```

i seem to recall that the default github token has access to everything, is that not the case?
