### ISSUE TITLE
Delete a Comment Without Creating a New One

### ISSUE THREAD

**Issue by joeyagreco-sb** [thollander/actions-comment-pull-request#251]
**Desired functionality:**

1. Workflow runs, creating a comment with tag `foo`
2. Workflow runs again, deletes the comment with tag `foo`

**Current functionality**

1. Workflow runs, creating a comment with tag `foo`
2. Workflow runs again, deletes the comment with tag `foo`
3. New comment is created in deletion step
a. Ideally, you would not have to create a new comment upon deletion of another comment

## Here's an example workflow snippet

```yaml
      - name: Post Comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            #### hello world
          comment_tag: foo
          mode: recreate

      - name: Delete Comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            #### Why do I need this to delete?
          comment_tag: foo
          mode: delete
          create_if_not_exists: false # thought this may fix it (it does not :/)
```

At the end of this, the `Post Comment` comment is deleted, but seemingly always replaced with a new comment that has the contents of the message in the `Delete Comment` step.

Ideally, there would be a way to delete an existing comment without creating a new one.

If there is a way to do this and I'm missing something here, please let me know

Thanks!

Update: seems this functionality may not be supported by GitHub: https://github.com/orgs/community/discussions/26256
