### ISSUE TITLE
Upload images

### ISSUE THREAD

**Issue by brunovollmer** [thollander/actions-comment-pull-request#255]
Hey,

great repo and action. I was wondering how hard it would be to add the option to also upload images as a comment into the PR conversation.

**Comment by thollander** [comment]
Hello, 

thanks ! 
It's actually already in place. 
Check out this example : https://github.com/thollander/actions-comment-pull-request/pull/6 

```
      - name: Comment PR with image
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: 'You can also put images... ![Placholder](https://via.placeholder.com/150.png)'
```
