### ISSUE TITLE
How to link to a file created in previous step of a github action?

### ISSUE THREAD

**Issue by ephraim271** [thollander/actions-comment-pull-request#265]
I am running pytest like this in one of the steps: 
pytest --html=test_rounding_results/report.html -s  --capture=tee-sys test_rounding.py 
So this test is triggered if there is a pull request. It stores the report.html in the test_rounding_results folder. However this is just part of the workspace runner (and is later uploaded as an artifact). 
Is it possible to link to this file somehow from the pull request comment created by the github-bot? 
Alternatively, is it possible for the action to "commit" the file and then link to it?

**Comment by thollander** [comment]
If you want to comment it from the file path, you can do it inside the same workflow : 

```
- name: PR comment with file
  uses: thollander/actions-comment-pull-request@v2
  with:
    filePath: test_rounding_results/report.html
```

However, if you need it in a different job, you need to download your artifact and then comment the PR with it. 
See https://github.com/actions/download-artifact#download-a-single-artifact 

Note : This action won't commit for you some files.
