### ISSUE TITLE
Question: how to use a file content as comment messages on a PR?

### ISSUE THREAD

**Issue by linrongbin16** [thollander/actions-comment-pull-request#295]
Hi, I'm trying to auto generate comments for new PRs in my repository.

I found this action, it looks like the `filePath` option can help me do these things:

* read the content from a file, for example: `pr-template.md` file (it has a markdown content, and it is complicated and cannot be directly put into this action as a `message`).
* use the content from the file as a `message`.

Here's my `pr.yml` actions:

```yaml
name: PR
on:
  pull_request: ~
  push:
    branches:
      - main
jobs:
  pr_comment:
    name: PR comment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: ls -lha
      shell: bash
      run: |
          echo "ls -lha ."
          ls -lha .
    - name: PR Comment
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: pr-template.md

```

But there's an error in my workflow:

https://github.com/linrongbin16/fzfx.nvim/actions/runs/6439036401/job/17486263012?pr=244

The error is:

`Error: Resource not accessible by integration`

<img width="906" alt="image" src="https://github.com/thollander/actions-comment-pull-request/assets/6496887/3d3fe061-a9a6-400a-8266-766f525844d5">

Would you please help me?
