### ISSUE TITLE
Changing icon and commenter name?

### ISSUE THREAD

**Issue by larseggert** [thollander/actions-comment-pull-request#359]
<img width="238" alt="Screenshot 2024-03-12 at 16 58 40" src="https://github.com/thollander/actions-comment-pull-request/assets/200328/cf8428b2-003d-4d90-b10b-8f454ebaa226">

Is there any way to change the commenter name, icon and/or URL that name and icon link to?

**Comment by alexVera99** [comment]
AFAIK, that's related witht the github token provided. In the documentation, they say it uses `${{ github.token }}` which I understand uses the github-actions user.

To change the icon an user name then you need to create a GH user, put the icon and user name you want. Create a token for that user and use it to run the action using the parameter `github-token`:
```yaml
- name: Write a comment that will be deleted at the end of the job
  uses: thollander/actions-comment-pull-request@v3
  with:
    message: |
      The PR is being built...
    github-token: ${{ secrets.YOUR_USER_TOKEN }}
```
