### ISSUE TITLE
How I can get a output of a file commented ? 

### ISSUE THREAD

**Issue by rafilkmp3** [thollander/actions-comment-pull-request#90]
I would like to put in a comment the content of a file

**Comment by thollander** [comment]
This may do the trick (not tested but you get the idea) : 

```yml
- name: Build comment
  uses: actions/github-script@v4
  if: github.event_name == 'pull_request'
  id: build-comment
  with:
    github-token: ${{ github.token }}
    result-encoding: string
    script: |
      const fs = require('fs');
      return fs.readFileSync('./YOUR_FILE').toString();

- name: Comment
  uses: thollander/actions-comment-pull-request@v1
  if: github.event_name == 'pull_request'
  with:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    message: ${{ steps.build-comment.outputs.result }}
```

You actually need to get the content of the file from another step and use it as an input parameter of this action.
